name: youbot
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: tombedor/youbot
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: discord_service
  routes:
  - path: /
  run_command: poetry run python youbot/service/discord_service.py