[tool.poetry]
name = "youbot"
version = "0.1.0"
description = ""
authors = ["Tom Bedor <tombedor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pgvector = "^0.2.4"
psycopg2-binary = "^2.9.9"
pymemgpt = {git = 'https://github.com/tombedor/MemGPT.git', rev='04658e7b02bafcaf418a20493e49a2cdd6278e8e'}
sqlalchemy = "^2.0.29"
discord = "^2.3.2"
celery = {extras = ["redis"], version = "^5.4.0"}
flask = "^3.0.2"
twilio = "^9.0.3"
gunicorn = "^21.2.0"
pyyaml = "^6.0.1"

[tool.pyright]
include = [
    "youbot/**/*.py",
    "tests/**/*.py"
]
exclude = [
    "**/__pycache__",
    ".venv",
    ".git",
    "dist",
    "build"
]
pythonVersion = "3.11"
verboseOutput = true
reportImportCycles = true
reportUnusedImport = true

[tool.black]
line-length = 140
target-version = ['py310', 'py311']

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"
black = {extras = ["jupyter"], version = "^24.4.2"}
autoflake = "^2.3.0"
pyright = "^1.1.350"
pytest = "^8.1.1"
fawltydeps = "^0.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
