packages:
    - name: web
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: receive_signup
          binary: false
          main: ""
          runtime: python:default
          web: true
          # webSecure: SECRET_VALUE
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
        - name: hello_world
          binary: false
          main: ""
          runtime: python:default
          web: true
          # webSecure: SECRET_VALUE
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}          