packages:
    - name: youbot_site
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: receive_signup
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}