from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from youbot.config import state_root
from youbot.models import AdapterRecord, CommandRecord, OverviewCommandSpec, RepoRecord
from youbot.utils import atomic_write, ensure_dir, now_iso


class AdapterLoader:
    def __init__(self) -> None:
        self._root = state_root() / "adapters" / "metadata"
        self._generated_root = state_root() / "adapters" / "generated"

    def refresh(self, repo: RepoRecord, commands: list[CommandRecord]) -> AdapterRecord:
        ensure_dir(self._root)
        ensure_dir(self._generated_root)
        overview_command = self._select_overview_command(repo, commands)
        adapter = AdapterRecord(
            adapter_id=f"{repo.repo_id}-adapter",
            repo_id=repo.repo_id,
            version="0.1.0",
            view_names=["overview", "conversation"],
            command_palette_entries=[command.command_name for command in commands],
            output_rules=["repo_overview_preview"],
            updated_at=now_iso(),
            overview_command=overview_command,
        )
        atomic_write(self._root / f"{repo.repo_id}.json", json.dumps(asdict(adapter), indent=2) + "\n")
        self._write_generated_notes(repo, adapter)
        return adapter

    def load(self, repo_id: str) -> AdapterRecord | None:
        path = self._root / f"{repo_id}.json"
        if not path.exists():
            return None
        payload = json.loads(path.read_text())
        overview_payload = payload.get("overview_command")
        overview_command = None
        if overview_payload is not None:
            overview_command = OverviewCommandSpec(**overview_payload)
        return AdapterRecord(
            adapter_id=payload["adapter_id"],
            repo_id=payload["repo_id"],
            version=payload["version"],
            view_names=payload["view_names"],
            command_palette_entries=payload["command_palette_entries"],
            output_rules=payload["output_rules"],
            updated_at=payload["updated_at"],
            overview_command=overview_command,
        )

    def _select_overview_command(
        self,
        repo: RepoRecord,
        commands: list[CommandRecord],
    ) -> OverviewCommandSpec | None:
        preferred_specs: dict[str, OverviewCommandSpec] = {
            "job_search": OverviewCommandSpec(
                command_name="pipeline-status",
                title="Pipeline Snapshot",
                max_lines=14,
                fallback_command_names=["next-actions", "active-openings"],
            ),
            "life_admin": OverviewCommandSpec(
                command_name="task-list",
                arguments=["5"],
                title="Top Tasks",
                max_lines=14,
                fallback_command_names=["task-digest", "cal-today"],
            ),
            "trader-bot": OverviewCommandSpec(
                command_name="research-program",
                title="Research Program",
                max_lines=14,
                fallback_command_names=["research-findings"],
            ),
        }
        preferred = preferred_specs.get(repo.repo_id)
        if preferred is not None and any(command.command_name == preferred.command_name for command in commands):
            return preferred

        fallback_candidates = ("status", "list", "overview", "summary")
        for command in commands:
            if any(token in command.command_name for token in fallback_candidates):
                return OverviewCommandSpec(
                    command_name=command.command_name,
                    title=f"{repo.repo_id} Overview",
                    max_lines=12,
                )
        return None

    def _write_generated_notes(self, repo: RepoRecord, adapter: AdapterRecord) -> None:
        lines = [
            f"# Generated adapter notes for {repo.repo_id}",
            "",
            f"Generated at: {adapter.updated_at}",
            f"Repo path: {repo.path}",
            "",
            "This file is generated by youbot during repo onboarding / refresh.",
            "It captures the current adapter decision so it can later be refined manually or regenerated.",
            "",
            "## Overview command",
        ]
        if adapter.overview_command is None:
            lines.append("No overview command was inferred.")
        else:
            lines.extend(
                [
                    f"- command: {adapter.overview_command.command_name}",
                    f"- arguments: {adapter.overview_command.arguments}",
                    f"- title: {adapter.overview_command.title}",
                    f"- max_lines: {adapter.overview_command.max_lines}",
                    f"- fallbacks: {adapter.overview_command.fallback_command_names}",
                ]
            )
        atomic_write(self._generated_root / f"{repo.repo_id}.md", "\n".join(lines) + "\n")
