from __future__ import annotations

from pathlib import Path

from youbot.adapters.defaults import PREFERRED_OVERVIEW_SECTIONS, PREFERRED_QUICK_ACTIONS
from youbot.core.models import (
    AdapterRecord,
    CommandRecord,
    OverviewSectionSpec,
    QuickActionSpec,
    RepoRecord,
)
from youbot.utils import atomic_write

BOILERPLATE_COMMANDS = {
    "default",
    "venv",
    "install",
    "sync",
    "format",
    "lint",
    "typecheck",
    "pyright",
    "test",
}
FALLBACK_OVERVIEW_TOKENS = ("status", "list", "overview", "summary")


def select_overview_sections(
    repo: RepoRecord,
    commands: list[CommandRecord],
) -> list[OverviewSectionSpec]:
    preferred = PREFERRED_OVERVIEW_SECTIONS.get(repo.repo_id)
    if preferred is not None:
        available = {command.command_name for command in commands}
        return [
            spec
            for spec in preferred
            if spec.command_name in available
            or any(name in available for name in spec.fallback_command_names)
        ]

    for command in commands:
        if any(token in command.command_name for token in FALLBACK_OVERVIEW_TOKENS):
            return [
                OverviewSectionSpec(
                    command_name=command.command_name,
                    title=f"{repo.repo_id} Overview",
                    max_lines=12,
                )
            ]
    return []


def select_quick_actions(repo: RepoRecord, commands: list[CommandRecord]) -> list[QuickActionSpec]:
    preferred = PREFERRED_QUICK_ACTIONS.get(repo.repo_id)
    available = {command.command_name for command in commands}
    if preferred is not None:
        return [spec for spec in preferred if spec.command_name in available]

    inferred: list[QuickActionSpec] = []
    for command in commands:
        if command.command_name in BOILERPLATE_COMMANDS:
            continue
        inferred.append(QuickActionSpec(command_name=command.command_name))
        if len(inferred) >= 4:
            break
    return inferred


def write_generated_notes(path: Path, repo: RepoRecord, adapter: AdapterRecord) -> None:
    lines = [
        f"# Generated adapter notes for {repo.repo_id}",
        "",
        f"Generated at: {adapter.updated_at}",
        f"Repo path: {repo.path}",
        "",
        "This file is generated by youbot during repo onboarding / refresh.",
        (
            "It captures the current adapter decision so it can later be refined "
            "manually or regenerated."
        ),
        "",
        "## Overview sections",
    ]
    if not adapter.overview_sections:
        lines.append("No overview sections were inferred.")
    else:
        for section in adapter.overview_sections:
            lines.extend(
                [
                    f"- command: {section.command_name}",
                    f"  arguments: {section.arguments}",
                    f"  title: {section.title}",
                    f"  render_mode: {section.render_mode}",
                    f"  max_lines: {section.max_lines}",
                    f"  fallbacks: {section.fallback_command_names}",
                ]
            )
    lines.extend(["", "## Quick actions"])
    if not adapter.quick_actions:
        lines.append("No quick actions were inferred.")
    else:
        for action in adapter.quick_actions:
            lines.extend(
                [
                    f"- command: {action.command_name}",
                    f"  title: {action.title}",
                    f"  arguments: {action.arguments}",
                ]
            )
    atomic_write(path, "\n".join(lines) + "\n")
